name: 'File Regex Replace'
description: 'Allows you to perform a regex replace in your repository files'
branding:
  icon: 'box'  
  color: 'green'
inputs:
  regex:
    description: 'regex to apply(regex)'
    required: true
  flags:
    description: 'flags of the regex'
    default: 'g'
    required: false
  replacement:
    description: 'replacement string'
    default: "$1"
    required: true
  dir:
    description: 'Directory to search for for files'
    default: '.'
    required: false
outputs:
  value:
    description: 'regex replaced in your repository files'
runs:
  using: 'node12'
  main: 'index.js'
