name: Build

on:
  - push
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: kkla320/regex-property-action@test
        with:
          regex: '(?<file>.*?).json'
          replacement: '$<file>.xml'
          include: 'package.json'
      - uses: actions/upload-artifact@v2  # upload to artifact to see the changes
        with:
          name: test
          path: |
            *.xml

